'use client'

import { createContext, useContext, useState, useCallback, ReactNode } from 'react'

export type Lang = 'ko' | 'en'

interface LanguageContextType {
  lang: Lang
  setLang: (lang: Lang) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Lang, Record<string, string>> = {
  ko: {
    // Header
    'header.brand': 'KPAI',
    'header.games': '게임',
    'header.features': '특징',
    'header.pricing': '가격',
    'header.donate': '기부하기',
    'header.subscribe': '구독하기',
    'header.signup': '회원가입',
    'header.login': '로그인',
    'header.logout': '로그아웃',
    'header.points': '포인트',
    'header.dailyCheckin': '출석',
    'header.settings': '설정',
    'header.admin': '관리자',
    'header.menu': '메뉴',
    // Hero
    'hero.title1': '아이들을 위한',
    'hero.title2': '교육 게임 플랫폼',
    'hero.desc': '7살 아이를 위한 재미있고 교육적인 웹 게임을 만나보세요. 글씨 드론, 로봇 조종, 네비게이션 등 다양한 웹 게임이 월 2,900원에 제공됩니다. 브라우저에서 다운로드 없이 바로 플레이할 수 있습니다.',
    'hero.ctaStart': '지금 시작하기',
    'hero.ctaGames': '게임 둘러보기',
    'hero.googleSignup': 'Google로 3초 가입',
    'hero.googleDataNotice': 'Google 로그인 시 이메일과 이름만 받아 계정을 생성합니다.',
    'hero.googleDataPurpose': '수집 목적: 계정 생성 및 로그인',
    'hero.legalPrefix': '계속하면',
    'hero.legalPrivacy': '개인정보처리방침',
    'hero.legalTerms': '이용약관',
    'hero.legalAnd': '및',
    'hero.legalSuffix': '에 동의한 것으로 봅니다.',
    'hero.gamesLabel': '다양한 게임',
    'hero.gamesList': '글씨 드론 · 로봇 조종 · 네비게이션',
    // Games
    'games.title': '웹 게임 소개',
    'games.subtitle': '브라우저에서 바로 플레이하는 다양한 웹 게임을 만나보세요',
    'games.drone.title': '글씨 드론 게임',
    'games.drone.desc': '손가락으로 글씨를 쓰면 드론이 그 경로를 따라 움직이는 재미있는 게임입니다.',
    'games.drone.status': '지금 플레이',
    'games.subway.title': '공항철도 지하철 게임',
    'games.subway.desc': '놀면서 배우는 공항철도 운행 체험: 운행의 재미와 돈 개념 학습을 동시에 잡은 어린이용 지하철 시뮬레이션',
    'games.subway.status': '지금 플레이',
    'games.subway.oneliner': '놀면서 배우는 공항철도 운행 체험: 운행의 재미와 돈 개념 학습을 동시에 잡은 어린이용 지하철 시뮬레이션',
    'games.subway.feature1': '어린이 맞춤 학습형 게임: 1명 탑승=1,000원, 출발비=500원으로 돈 개념을 쉽게 익힐 수 있습니다.',
    'games.subway.feature2': '실제 노선 기반 운행: 공항철도(AREX) 전체 역을 따라 왕복 주행하며 역 이름과 흐름을 자연스럽게 배웁니다.',
    'games.subway.feature3': '직관적인 조작: 문 열기/닫기, 출발, 가속만으로 플레이 가능해 저연령도 쉽게 즐길 수 있습니다.',
    'games.subway.feature4': '단계별 음성 안내(TTS): 상황별 안내 문구를 읽어줘서 글 읽기가 익숙하지 않은 아이도 따라할 수 있습니다.',
    'games.subway.feature5': '승하차 시각화: 승객이 한 명씩 타고 내리는 장면과 함께 수익이 즉시 반영되어 학습 몰입도가 높습니다.',
    'games.subway.feature6': '실감형 운행 연출: 가속·감속, 역 정차, 신호등, 터널 통과, 다리 구간(물 흐름) 등 실제 운행 느낌을 제공합니다.',
    'games.subway.feature7': '환경 변화 시스템: 낮/노을/밤, 비/안개가 자동 전환되고 조명(전조등·역 조명)도 상황에 맞게 점등됩니다.',
    'games.subway.feature8': '위치 인지 미니맵: 현재 열차 위치, 이동 구간, 역 정보를 한눈에 확인할 수 있어 공간 감각을 키울 수 있습니다.',
    'games.subway.feature9': '혼잡도 시뮬레이션: 역별 혼잡 상태(여유/보통/혼잡)가 색상으로 표현되어 상황 판단 학습에 도움이 됩니다.',
    'games.subway.feature10': '반응형 UI/UX: 모바일과 데스크톱 모두에서 안정적으로 플레이할 수 있도록 UI를 최적화했습니다.',
    'games.subway.featuresTitle': '특장점 요약',
    'games.subway.playButton': '지금 플레이',
    'games.robot.title': '로봇 조종 게임',
    'games.robot.desc': '7살 아이가 로봇을 조종해서 목적지를 찾아가는 미션 게임입니다.',
    'games.robot.status': '곧 출시 예정',
    'games.nav.title': '네비게이션 게임',
    'games.nav.desc': '네비로 길을 찾아가며 공간 인지력을 키우는 교육 게임입니다.',
    'games.nav.status': '곧 출시 예정',
    'games.more.title': '더 많은 게임',
    'games.more.desc': '새로운 게임이 계속 추가될 예정입니다. 기대해주세요!',
    'games.more.status': '준비 중',
    // Features
    'features.title': '플랫폼 특징',
    'features.subtitle': 'KPAI 플랫폼의 특징을 만나보세요',
    'features.f1.title': '다양한 교육 게임',
    'features.f1.desc': '글씨 드론, 로봇 조종, 네비게이션 등 아이들을 위한 다양한 게임을 제공합니다.',
    'features.f2.title': '교육적 가치',
    'features.f2.desc': '재미있게 놀면서 자연스럽게 학습할 수 있는 교육 게임입니다.',
    'features.f3.title': '7살 아이 맞춤',
    'features.f3.desc': '7살 아이의 발달 단계에 맞춘 직관적이고 쉬운 조작법을 제공합니다.',
    'features.f4.title': '계속 추가되는 게임',
    'features.f4.desc': '새로운 게임이 계속 추가되어 더 많은 재미를 경험할 수 있습니다.',
    'features.f5.title': '합리적인 가격',
    'features.f5.desc': '모든 게임을 월 2,900원으로 이용할 수 있는 합리적인 구독제입니다.',
    'features.f6.title': '간편한 사용',
    'features.f6.desc': 'PC, 스마트폰, 태블릿 브라우저에서 다운로드 없이 바로 웹 게임을 플레이할 수 있습니다.',
    // HowItWorks
    'how.title': '이용 방법',
    'how.subtitle': '간단한 4단계로 게임을 시작하세요',
    'how.step1.title': '구독하기',
    'how.step1.desc': '월 2,900원으로 구독하고 모든 게임에 접근하세요.',
    'how.step2.title': '웹에서 접속',
    'how.step2.desc': 'PC, 스마트폰, 태블릿 브라우저에서 사이트에 접속하세요.',
    'how.step3.title': '웹 게임 플레이',
    'how.step3.desc': '글씨 드론, 로봇 조종, 네비게이션 등 원하는 웹 게임을 즐기세요.',
    'how.step4.title': '새로운 웹 게임',
    'how.step4.desc': '계속 추가되는 새로운 웹 게임을 자동으로 이용할 수 있습니다!',
    // Pricing
    'pricing.title': '구독 가격',
    'pricing.subtitle': '모든 웹 게임을 월 2,900원에 이용하세요',
    'pricing.note': '사용자 확보를 위해 특별 가격으로 제공됩니다',
    'pricing.planName': '월간 구독',
    'pricing.price': '₩2,900',
    'pricing.planDesc': '모든 웹 게임을 월 2,900원에 이용하세요',
    'pricing.f1': '모든 웹 게임 무제한 플레이',
    'pricing.f2': '글씨 드론 웹 게임',
    'pricing.f3': '로봇 조종 웹 게임 (출시 예정)',
    'pricing.f4': '네비게이션 웹 게임 (출시 예정)',
    'pricing.f5': '새로운 웹 게임 자동 추가',
    'pricing.f6': '광고 없음',
    'pricing.f7': '언제든지 취소 가능',
    'pricing.subscribe': '구독하기',
    'pricing.startFree': '무료로 시작하기',
    'pricing.popular': '인기',
    // Download/Play
    'play.title': '지금 웹에서 플레이하세요',
    'play.subtitle': 'KPAI 플랫폼에서 구독 후 브라우저로 바로 게임을 즐기세요',
    'play.cta': '구독하고 웹에서 플레이하기',
    'play.browser': '브라우저 지원',
    'play.browserDesc': 'PC, 스마트폰, 태블릿 브라우저에서 바로 플레이',
    'play.various': '다양한 웹 게임',
    'play.variousDesc': '계속 추가되는 새로운 웹 게임',
    'play.update': '정기 업데이트',
    'play.updateDesc': '새로운 웹 게임과 기능 지속 추가',
    // Donate
    'donate.title': '기부하기',
    'donate.subtitle': 'KPAI 플랫폼을 후원해 주시면 더 많은 교육 게임 개발에 힘이 됩니다.',
    'donate.note': '아래 계좌로 이체해 주시면 감사하겠습니다.',
    'donate.bank': '은행',
    'donate.account': '계좌번호',
    'donate.holder': '예금주',
    'donate.copy': '복사',
    'donate.copied': '복사됨',
    'donate.thanks': '기부 후 원하시면 문의 메일로 알려 주시면 감사 인사 드리겠습니다.',
    // Footer
    'footer.brand': 'KPAI',
    'footer.desc': '아이들을 위한 교육 웹 게임 플랫폼입니다.',
    'footer.games': '게임',
    'footer.gameIntro': '게임 소개',
    'footer.platformFeatures': '플랫폼 특징',
    'footer.subscribePrice': '구독 가격',
    'footer.donate': '기부하기',
    'footer.support': '지원',
    'footer.customerSupport': '고객 지원',
    'footer.faq': '자주 묻는 질문',
    'footer.contact': '문의하기',
    'footer.contactTitle': '연락처',
    'footer.emailNote': '메일로 문의 시 처리 가능합니다.',
    'footer.email1': '일반 문의',
    'footer.email2': '운영 담당',
    'footer.legal': '정책',
    'footer.privacy': '개인정보처리방침',
    'footer.terms': '이용약관',
    'footer.dataDeletion': '데이터 삭제 안내',
    'footer.copyright': 'KPAI. All rights reserved.',
    // Success
    'success.title': '결제 완료!',
    'success.desc': '구독이 성공적으로 완료되었습니다. 이제 모든 프리미엄 기능을 사용하실 수 있습니다.',
    'success.goPlay': '웹 게임 하러 가기',
    'success.goHome': '홈으로 돌아가기',
    'payment.loading': '처리 중...',
    'payment.subscribe': '구독하기',
    // Drone Select (미리보기)
    'droneSelect.soundOff': 'SOUND OFF',
    'droneSelect.survival': '생존 확률: 1.11% (약 1/90)',
    'droneSelect.round': 'ROUND 1: 드론 10대 중 살아남을 드론을 선택하세요. (15초 내 미선택 시 자동 진행)',
    'droneSelect.confirm': '선택 완료',
    'droneSelect.sectionTitle': '드론 선택 게임 미리보기',
  },
  en: {
    'header.brand': 'KPAI',
    'header.games': 'Games',
    'header.features': 'Features',
    'header.pricing': 'Pricing',
    'header.donate': 'Donate',
    'header.subscribe': 'Subscribe',
    'header.signup': 'Sign up',
    'header.login': 'Log in',
    'header.logout': 'Log out',
    'header.points': 'Points',
    'header.dailyCheckin': 'Check-in',
    'header.settings': 'Settings',
    'header.admin': 'Admin',
    'header.menu': 'Menu',
    'hero.title1': 'Educational',
    'hero.title2': 'Game Platform for Kids',
    'hero.desc': 'Fun, educational web games for 7-year-olds. Play handwriting drone, robot control, navigation and more for ₩2,900/month. No download—play in your browser.',
    'hero.ctaStart': 'Get Started',
    'hero.ctaGames': 'Browse Games',
    'hero.googleSignup': 'Sign up with Google in 3 seconds',
    'hero.googleDataNotice': 'We only use your Google email and name to create your account.',
    'hero.googleDataPurpose': 'Purpose: account creation and login',
    'hero.legalPrefix': 'By continuing, you agree to our',
    'hero.legalPrivacy': 'Privacy Policy',
    'hero.legalTerms': 'Terms of Service',
    'hero.legalAnd': 'and',
    'hero.legalSuffix': '.',
    'hero.gamesLabel': 'Various Games',
    'hero.gamesList': 'Drone · Robot · Navigation',
    'games.title': 'Web Games',
    'games.subtitle': 'Play a variety of web games right in your browser',
    'games.drone.title': 'Handwriting Drone Game',
    'games.drone.desc': 'Draw with your finger and the drone follows the path.',
    'games.drone.status': 'Play Now',
    'games.subway.title': 'Airport Railroad (Subway) Game',
    'games.subway.desc': 'Learn by playing: Airport Railroad driving experience—fun operation and money concepts for kids in one subway simulation.',
    'games.subway.status': 'Play Now',
    'games.subway.oneliner': 'Learn by playing: Airport Railroad driving experience—fun operation and money concepts for kids in one subway simulation.',
    'games.subway.feature1': 'Kids learning game: ₩1,000 per passenger, ₩500 departure fee so children learn money concepts easily.',
    'games.subway.feature2': 'Real route: Full AREX stations, round-trip driving so kids learn station names and flow naturally.',
    'games.subway.feature3': 'Simple controls: Open/close doors, depart, accelerate—easy for young children.',
    'games.subway.feature4': 'Step-by-step TTS: Voice guidance so even pre-readers can follow.',
    'games.subway.feature5': 'Boarding visualization: See passengers get on/off and revenue update in real time for better engagement.',
    'games.subway.feature6': 'Realistic driving: Acceleration, braking, stops, signals, tunnels, bridge section for an authentic feel.',
    'games.subway.feature7': 'Time & weather: Day/sunset/night, rain/fog with matching headlights and station lights.',
    'games.subway.feature8': 'Minimap: Current position, route, and station info at a glance to build spatial awareness.',
    'games.subway.feature9': 'Congestion simulation: Station crowding (comfortable/normal/crowded) shown by color for situational learning.',
    'games.subway.feature10': 'Responsive UI: Optimized for stable play on both mobile and desktop.',
    'games.subway.featuresTitle': 'Key features',
    'games.subway.playButton': 'Play Now',
    'games.robot.title': 'Robot Control Game',
    'games.robot.desc': 'Guide the robot to the goal in this mission game for kids.',
    'games.robot.status': 'Coming Soon',
    'games.nav.title': 'Navigation Game',
    'games.nav.desc': 'Build spatial awareness by finding your way.',
    'games.nav.status': 'Coming Soon',
    'games.more.title': 'More Games',
    'games.more.desc': 'New games are on the way. Stay tuned!',
    'games.more.status': 'Coming Soon',
    'features.title': 'Platform Features',
    'features.subtitle': 'What KPAI offers',
    'features.f1.title': 'Various Educational Games',
    'features.f1.desc': 'Handwriting drone, robot control, navigation and more for kids.',
    'features.f2.title': 'Educational Value',
    'features.f2.desc': 'Learn while having fun with our educational games.',
    'features.f3.title': 'Made for Age 7',
    'features.f3.desc': 'Simple, intuitive controls designed for 7-year-olds.',
    'features.f4.title': 'Growing Library',
    'features.f4.desc': 'New games are added regularly for more fun.',
    'features.f5.title': 'Fair Price',
    'features.f5.desc': 'All games for ₩2,900/month with one subscription.',
    'features.f6.title': 'Easy to Use',
    'features.f6.desc': 'Play web games in your browser on PC, phone, or tablet—no download.',
    'how.title': 'How It Works',
    'how.subtitle': 'Get started in 4 simple steps',
    'how.step1.title': 'Subscribe',
    'how.step1.desc': 'Subscribe for ₩2,900/month to access all games.',
    'how.step2.title': 'Open in Browser',
    'how.step2.desc': 'Visit the site on your PC, phone, or tablet.',
    'how.step3.title': 'Play Web Games',
    'how.step3.desc': 'Enjoy handwriting drone, robot, navigation and more.',
    'how.step4.title': 'New Games',
    'how.step4.desc': 'New web games are added automatically to your subscription.',
    'pricing.title': 'Pricing',
    'pricing.subtitle': 'All web games for ₩2,900/month',
    'pricing.note': 'Special launch price to grow our community.',
    'pricing.planName': 'Monthly',
    'pricing.price': '₩2,900',
    'pricing.planDesc': 'Access all web games for ₩2,900/month',
    'pricing.f1': 'Unlimited play for all web games',
    'pricing.f2': 'Handwriting drone web game',
    'pricing.f3': 'Robot control game (Coming soon)',
    'pricing.f4': 'Navigation game (Coming soon)',
    'pricing.f5': 'New web games added automatically',
    'pricing.f6': 'No ads',
    'pricing.f7': 'Cancel anytime',
    'pricing.subscribe': 'Subscribe',
    'pricing.startFree': 'Start Free',
    'pricing.popular': 'Popular',
    'play.title': 'Play on the Web Now',
    'play.subtitle': 'Subscribe and play KPAI web games right in your browser',
    'play.cta': 'Subscribe & Play on Web',
    'play.browser': 'Browser Support',
    'play.browserDesc': 'Play on PC, phone, or tablet browser',
    'play.various': 'Various Web Games',
    'play.variousDesc': 'New web games added regularly',
    'play.update': 'Regular Updates',
    'play.updateDesc': 'New web games and features added often',
    'donate.title': 'Donate',
    'donate.subtitle': 'Support KPAI to help us build more educational games.',
    'donate.note': 'Thank you for sending your support to the account below.',
    'donate.bank': 'Bank',
    'donate.account': 'Account',
    'donate.holder': 'Account Holder',
    'donate.copy': 'Copy',
    'donate.copied': 'Copied',
    'donate.thanks': 'You may contact us by email after donating if you’d like a thank-you note.',
    'footer.brand': 'KPAI',
    'footer.desc': 'Educational web game platform for kids.',
    'footer.games': 'Games',
    'footer.gameIntro': 'Games',
    'footer.platformFeatures': 'Features',
    'footer.subscribePrice': 'Pricing',
    'footer.donate': 'Donate',
    'footer.support': 'Support',
    'footer.customerSupport': 'Support',
    'footer.faq': 'FAQ',
    'footer.contact': 'Contact',
    'footer.contactTitle': 'Contact',
    'footer.emailNote': 'We respond to inquiries by email.',
    'footer.email1': 'General',
    'footer.email2': 'Operations',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.dataDeletion': 'Data Deletion',
    'footer.copyright': 'KPAI. All rights reserved.',
    'success.title': 'Payment Complete!',
    'success.desc': 'Your subscription is active. You can now use all premium features.',
    'success.goPlay': 'Go to Web Games',
    'success.goHome': 'Back to Home',
    'payment.loading': 'Processing...',
    'payment.subscribe': 'Subscribe',
    'droneSelect.soundOff': 'SOUND OFF',
    'droneSelect.survival': 'Survival rate: 1.11% (approx. 1/90)',
    'droneSelect.round': 'ROUND 1: Select the drone that will survive among 10 drones. (Auto-progress in 15 sec if no selection)',
    'droneSelect.confirm': 'Confirm selection',
    'droneSelect.sectionTitle': 'Drone selection game preview',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('ko')

  const setLang = useCallback((newLang: Lang) => {
    setLangState(newLang)
    if (typeof document !== 'undefined') {
      document.documentElement.lang = newLang === 'ko' ? 'ko' : 'en'
    }
  }, [])

  const t = useCallback((key: string) => {
    return translations[lang]?.[key] ?? translations['ko'][key] ?? key
  }, [lang])

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
